# Generated by Django 4.0.4 on 2023-04-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exampleApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transformer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', models.JSONField()),
                ('priorityRanking', models.IntegerField()),
                ('timeElapsed', models.IntegerField()),
                ('resolved', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
